Infer
Parzival-05/comp24 pull request #3
Opened 2024-11-01 08:20 UTC by ancavar

Пока как есть, мне офк не нравится как я хэндлю TVar (поменял fresh на string и в некоторый местах делаю int_of_string и string_of_int 🫣🫣🫣), как в окамле прям сделать с сохранением пользовательских типов ('test) сложно... 

еще тесты переместил, надеюсь ты не против (хотя их вообще из папки libs надо вынести)

2024-11-01 14:13 UTC, Parzival-05 requested changes
🔝

2024-11-01 14:13 UTC, Parzival-05 commented on HTML/lib/tests/inferencerTests.ml
> +end
Тесты гуд, но не хватает проверок:
- замыканий
![image](https://github.com/user-attachments/assets/3ba1b236-3bbc-429f-9795-602bd5a146ef)
- occur check
![image](https://github.com/user-attachments/assets/87ac726b-73b7-4ac6-a808-180a1104f6cc)

Сделаешь?

2024-11-01 14:13 UTC, Parzival-05 commented on HTML/lib/inferencer.ml
> +(** Copyright 2024-2025, Dmitrii Kosarev, David Akhmedov, Danil Parfyonov *)
Не хватает mli файла. Можно добавить его после фиксов и доработок.

2024-11-01 17:02 UTC, ancavar commented on HTML/lib/inferencer.ml
> +;;
Ради двух функций отдельный файлик стоит того? я бы просто в typing.ml запихнул, но если ты настаиваешь....

2024-11-01 17:13 UTC, ancavar commented on HTML/lib/tests/inferencerTests.ml
> +end
а как это смотреть так построчно?

2024-11-01 17:38 UTC, ancavar commented on HTML/lib/inferencer.ml
> +;;
короче если ты не против я потом могу попробовать все по папкам раскидать в следующем ПР

2024-11-01 23:30 UTC, Parzival-05 commented on HTML/lib/tests/inferencerTests.ml
> +end
Загляни в makefile

2024-11-02 20:42 UTC, Parzival-05 commented
Подправил АСТ: парсер не может знать, оператор бинарный или унарный, поэтому нельзя было правильно инферить. Знание о том, в скобках ли операция, и контекст исполнения должны позволять однозначно инферить выражения c оператором.

2025-02-03 15:16 UTC, merged